name: Run Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build clang-19
          version: 1.0

      - name: Build tests
        run: |
          chmod +x ./build.sh
          ./build.sh test
          ninja -v -C build/test
        shell: bash

      - name: Run tests
        run: ctest --test-dir build/test --verbose
