name: Run Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-19

      - name: Build tests
        run: |
          chmod +x ./build.sh
          ./build.sh test
          ninja -v -C build/test

      - name: Run tests
        run: ctest --test-dir build/test --verbose
